<Tela1>:
    orientation: "vertical"
    Button:
        text: "Clique"
        # invocando a c função na classe tela1
        on_press: root.on_press_bt()
    Button:
        text: "bt2"
    Button:
        text: "bt3"

<Tela2>:
    orientation: "vertical"
    Button:
        text: "Clique"
        on_press: root.on_press_bt()

Tela1: # criando uma instancia
       # só criar uma instancia (raiz)